# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - variamos-ms-restrictions

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_b3ffecd9aa7242d0baec9b1350f7b08d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4397e9339a4f4b039d0bc20fd6619573 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_b3ffecd9aa7242d0baec9b1350f7b08d }}/magudeloz/variamos_ms_restrictions:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'variamos-ms-restrictions'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_8c80e36f06064c2d93cccc777f5da9b8 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_b3ffecd9aa7242d0baec9b1350f7b08d }}/magudeloz/variamos_ms_restrictions:${{ github.sha }}'